version: '3.8'

networks:
  algo-net:
    driver: bridge

services:
  nginxproxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.nginx:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/live/p.ssafy.io:/etc/nginx/ssl:ro
    restart: always
  backend:
    depends_on:
      - nginxproxy
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JASYPT_KEY=${JASYPT_KEY}
    networks:
      - algo-net
  front:
    depends_on:
      - nginxproxy
    build:
      context: ./front_react
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    networks:
      - algo-net
  execute:
    depends_on:
      - nginxproxy
    build:
      context: ./execute
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8082"
    networks:
      - algo-net
