version: '3.8'

networks:
  algo-net:
    driver: bridge

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    # ports:
    #   - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JASYPT_KEY=${JASYPT_KEY}
    networks:
      - algo-net
  front:
    build:
      context: ./front_react
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/p.ssafy.io:/etc/nginx/ssl:ro
    networks:
      - algo-net
  execute:
    build:
      context: ./execute
      dockerfile: Dockerfile
    # ports:
    #   - "8082:8082"
    networks:
      - algo-net
